command_key:
    web: "(?P<key>[a-zA-Z0-9_]+) (?P<url>.+)"

help:
  maya:
  maxscript: http://docs.autodesk.com/3DSMAX/16/ENU/MAXScript-Help/
  nuke_python: https://www.thefoundry.co.uk/products/nuke/developers/100/pythonreference/
  houdini:
  nuke: https://www.thefoundry.co.uk/products/nuke/developers/100/pythonreference/

